config/routes.rb
Convoyd::Application.routes.draw do
  

  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"
  
  get "convoyd_files/:id/authenticate" => "convoyd_files#authenticate", :as => "authenticate_for_file"
  match "convoyd_files/:id/check_authentication" => "convoyd_files#check_authentication", :as => "check_authentication"
  
  match 'convoyd_files/:id/download' => "convoyd_files#download", :as => "download_convoyd_file"
  
  
  resources :users, :shallow => true do
    resources :convoyd_files 
  end
  
  resources :sessions
  

  root :to => 'sessions#new'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user permission to do.
    # If you pass :manage it will apply to every action. Other common actions here are
    # :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. If you pass
    # :all it will apply to every resource. Otherwise pass a Ruby class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details: https://github.com/ryanb/cancan/wiki/Defining-Abilities
  
    user ||= User.new # guest user (not logged in)
    if user.admin?
      can :manage, :all
    elsif user.full_user?
      can :manage, ConvoydFile, :user_id => user.id
      can :manage, User, :id => user.id 
    else
      can :read, ConvoydFile, :status => "unlocked"
    end

  end
end

app/models/convoyd_file.rb
require 'bcrypt'

class ConvoydFile < ActiveRecord::Base
  
  authenticates_with_sorcery!
  
  belongs_to :user
  
  attr_accessible :upload, :user_id, :set_pass, :notification
  attr_accessor :notification, :set_pass
  
  # before_save :encrypt_password
  
  # validates_confirmation_of :password
  
  
  has_attached_file :upload, 
    :storage => :s3,
    :bucket => 'uploads.convoyd.com',
    :s3_credentials => {
      :access_key_id => S3[:key],
      :secret_access_key => S3[:secret]
    },
    :s3_permissions => :private,
    :path => ":attachment/:id/:style/:filename"
  
  validates_attachment_presence :upload
  validates_attachment_size :upload, :less_than => 500.megabytes
  
  STATUSES = %w[locked unlocked]
  
  
  def encrypt_password
    if password.present?
      self.crypted_password = BCrypt::Password.create(password)
    end
  end
  
  
  def password_authentic?(password)
    self.crypted_password == password
    # BCrypt::Password.new(self.crypted_password) == password
  end
    
  
  def requires_password?
    self.crypted_password.present?
  end
  
  
  def authenticated?(file_id)
    file_id == self.id
  end
  
  
  def set_random_password
    self.crypted_password = ConvoydFile.random_password(10)
    self.save
  end
  
    
  protected

  def self.random_password(length)
    rand(36**length).to_s(36)
  end
  
end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!
  
  attr_accessible :first_name, :last_name, :email, :password, :password_confirmation

  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email
  
  has_many :convoyd_files, :dependent => :destroy
  
  # Define user roles
  ROLES = %w[limited_user full_user moderator admin]
  STATUSES = %w[unapproved disabled active]
  
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  protect_from_forgery
  
  rescue_from CanCan::AccessDenied do |exception|
    redirect_to login_path, :alert => exception.message
  end
  
  
  private
    
  def not_authenticated
    redirect_to login_url, :alert => "First log in to view this page."
  end
  
  
  
end

app/controllers/convoyd_files_controller.rb
class ConvoydFilesController < ApplicationController
    
  
  def index
    @convoyd_files = ConvoydFile.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @convoyd_files }
    end
  end

  # GET /convoyd_files/1
  # GET /convoyd_files/1.json
  def show
    @convoyd_file = ConvoydFile.find(params[:id])
    if @convoyd_file.requires_password? && !@convoyd_file.authenticated?(session[:file_id])
      redirect_to authenticate_for_file_path(@convoyd_file)
    end
  end

  # GET /convoyd_files/new
  # GET /convoyd_files/new.json
  def new
    @convoyd_file = ConvoydFile.new
    @user = User.find(params[:user_id])

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @convoyd_file }
    end
  end

  # GET /convoyd_files/1/edit
  def edit
    @convoyd_file = ConvoydFile.find(params[:id])
  end

 
  def create
    @convoyd_file = ConvoydFile.new(params[:convoyd_file])
    @user = User.find(params[:user_id])
    emails = params[:convoyd_file][:notification]
    @convoyd_file.set_random_password if params[:convoyd_file][:set_pass] == "1"

    if @convoyd_file.save
      Notifier.upload_notification(@convoyd_file, emails).deliver if emails.present?
      redirect_to user_path(@user), :notice => 'Convoyd file was successfully created.'
    else
      render action: "new" 
    end
  end

  # PUT /convoyd_files/1
  # PUT /convoyd_files/1.json
  def update
    @convoyd_file = ConvoydFile.find(params[:id])

    respond_to do |format|
      if @convoyd_file.update_attributes(params[:convoyd_file])
        format.html { redirect_to @convoyd_file, notice: 'Convoyd file was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @convoyd_file.errors, status: :unprocessable_entity }
      end
    end
  end

 
  def destroy
    @convoyd_file = ConvoydFile.find(params[:id])
    @user = User.find(params[:user_id])
    @convoyd_file.destroy

    redirect_to user_path(@user)
  end
  
  
  def download
    @convoyd_file = ConvoydFile.find(params[:id])
    redirect_to @convoyd_file.upload.expiring_url(10)
  end
  
  
  def authenticate
    @convoyd_file = ConvoydFile.find(params[:id])
  end
  
  def check_authentication
    @convoyd_file = ConvoydFile.find(params[:id])
    if @convoyd_file.password_authentic?(params[:password])
       session[:file_id] = @convoyd_file.id
       redirect_to convoyd_file_path(@convoyd_file)
     else
       redirect_to authenticate_for_file_path(@convoyd_file), :notice => 'Authentication failed!'
    end
  end
  
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new

  end


  def create
    user = login(params[:email], params[:password], params[:remember_me])
    if user
      redirect_back_or_to user_path(current_user), :notice => "Logged in!"
    else
      redirect_to login_path, :notice => "Email or password was invalid."
    end
  end
  
  
  def destroy
    logout
    redirect_to login_path, :notice => "Logged out!"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
 
  before_filter :require_login
 
  def index
    @users = User.all
  end

  
  def show
    @user = User.find(params[:id])
  end

 
  def new
    @user = User.new
  end


  def edit
    @user = User.find(params[:id])
  end

 
  def create
    @user = User.new(params[:user])

    if @user.save
      redirect_to users_path, :notice => 'User was successfully created.' 
    else
      render :new
    end
  end

 
  def update
    @user = User.find(params[:id])

    if @user.update_attributes(params[:user])
      redirect_to users_path, :notice => 'User was successfully updated.'
    else
      render :edit
    end
  end

 
  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/convoyd_files_helper.rb
module ConvoydFilesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/convoyd_files/_form.html.erb
<%= form_for([@user, @convoyd_file], :html => {:multipart => true}) do |f| %>
 	<% if @convoyd_file.errors.any? %>
   		<div id="error_explanation">
     		<h2><%= pluralize(@convoyd_file.errors.count, "error") %> prohibited this file from being uploaded:</h2>
     		<ul>
     			<% @convoyd_file.errors.full_messages.each do |msg| %>
       				<li><%= msg %></li>
     			<% end %>
     		</ul>
   		</div>
 	<% end %>

 	<%= f.hidden_field :user_id, :value => @user.id %>
	<p>Select your file</p>
 	<div class="field">
   		<%= f.file_field :upload %>
 	</div>
	<p>Tell us who we should email.  Separate multiple emails with a comma.</p>
	<div class="field">
   		<%= f.text_field :notification %>
 	</div>
	<p>Give file a random password?</p>
	<div class="field">
   		<%= f.check_box :set_pass %>
 	</div>
 	<div class="actions">
   		<%= f.submit "Upload!" %>
 	</div>
<% end %>

app/views/convoyd_files/authenticate.html.erb
<h1>Enter the Password!</h1>

<%= form_tag({:controller => "convoyd_files", :action => "check_authentication"}) do %>
  <div class="field">
    <%= label_tag :password %>
    <%= password_field_tag :password %>
  </div>
  <div class="actions"><%= submit_tag "Authenticate!" %></div>
<% end %>

app/views/convoyd_files/edit.html.erb
<h1>Editing convoyd_file</h1>

<%= render 'form' %>

<%= link_to 'Show', @convoyd_file %> |
<%= link_to 'Back', convoyd_files_path %>

app/views/convoyd_files/index.html.erb
<h1>Listing convoyd_files</h1>

<table>
  <tr>
    <th>User</th>
    <th>Upload file size</th>
    <th>Upload content type</th>
    <th>Upload file name</th>
    <th>Upload updated at</th>
    <th>Upload</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @convoyd_files.each do |convoyd_file| %>
  <tr>
    <td><%= convoyd_file.user_id %></td>
    <td><%= convoyd_file.upload_file_size %></td>
    <td><%= convoyd_file.upload_content_type %></td>
    <td><%= convoyd_file.upload_file_name %></td>
    <td><%= convoyd_file.upload_updated_at %></td>
    <td><%= convoyd_file.upload %></td>
    <td><%= link_to 'Show', convoyd_file %></td>
    <td><%= link_to 'Edit', edit_convoyd_file_path(convoyd_file) %></td>
    <td><%= link_to 'Destroy', convoyd_file, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Convoyd file', new_user_convoyd_file_path %>

app/views/convoyd_files/new.html.erb
<h1>Upload a File!</h1>

<%= render 'form' %>

<%= link_to 'Back', user_path(@user) %>

app/views/convoyd_files/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <%= @convoyd_file.user.first_name %>'s file
</p>

<p>
	<b>Download it here</b>: <%= link_to "#{@convoyd_file.upload_file_name}", download_convoyd_file_path(@convoyd_file) , :target => "_blank"  %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CONVOYD - Easy File Uploading</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= params[:controller] %>">
  <div id="container">
    <div class="user_nav">
      <% if current_user %>
        Logged in as <%= current_user.email %>
        <%= link_to "Log out", logout_path %>
      <% else %>
        <%= link_to "Log in", login_path  %>
      <% end %>
    </div>
    <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    <% end %>
	<br />
    <%= yield %>
  </div>
</body>
</html>

app/views/notifier/upload_notification.text.erb
Hey there,

I just uploaded a file for you on Convoyd.  You can download it by going here and clicking on the Download link:

<%= ENV['URL_PREFIX'] + convoyd_file_path(@convoyd_file) %>

<% if @convoyd_file.crypted_password.present? %>
You'll need this password to access that file:

<%= @convoyd_file.crypted_password %>
<% end %>

Enjoy!

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
	<% if @user.errors.any? %>
	  <div id="error_explanation">
	    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

	    <ul>
	    <% @user.errors.full_messages.each do |msg| %>
	      <li><%= msg %></li>
	    <% end %>
	    </ul>
	  </div>
	<% end %>

	<div class="field">
	  <%= f.label :first_name %><br />
	  <%= f.text_field :first_name %>
	</div>
	<div class="field">
	  <%= f.label :last_name %><br />
	  <%= f.text_field :last_name %>
	</div>
	<div class="field">
	  <%= f.label :email %><br />
	  <%= f.text_field :email %>
	</div>
	<div class="field">
	  <%= f.label :password %>
	  <%= f.password_field :password %>
	</div>
	<div class="field">
	  <%= f.label :password_confirmation %>
	  <%= f.password_field :password_confirmation %>
	</div>
	<div class="field">
	  <%= f.label :quota %><br />
	  <%= f.text_field :quota %>
	</div>
	<div class = "field">
		<%= f.label :role %><br />
		<%= f.collection_select :role, User::ROLES, :to_s, :humanize %>
	</div>
	<div class = "field">
		<%= f.label :status %><br />
		<%= f.collection_select :status, User::STATUSES, :to_s, :humanize %>
	</div>	

	<div class="actions">
	  <%= f.submit %>
	</div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>First name</th>
    <th>Last name</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.first_name %></td>
    <td><%= user.last_name %></td>
    <td><%= user.email %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<h1><%= @user.first_name %> <%= @user.last_name %>'s Uploads</h1>

<p>Here are all the files you've uploaded:</p>

<p><em>Remember, files are automatically deleted after 48 hours.</em><p>

<% if @user.convoyd_files.present? %>
	<% for convoyd_file in @user.convoyd_files %>
		<ul>
			<li>
				<%= link_to "#{convoyd_file.upload_file_name}", download_convoyd_file_path(convoyd_file) , :target => "_blank"  %>,
				 uploaded <%= convoyd_file.created_at %>
				<%= button_to "Delete", { :controller => 'convoyd_files', :action => 'destroy', :id => convoyd_file.id, :user_id => @user.id },
					:confirm => "Are you sure you want to delete the file #{convoyd_file.upload_file_name}?", :method => :delete %>
			</li>	
		</ul>		
	<% end %>
<% else %>
	 <p><em>You haven't uploaded anything yet.</em></p>
<% end %>	
		
<%= link_to 'Upload a New File', new_user_convoyd_file_path(@user) %><br /><br />
		